import React from "react";
<<<<<<< HEAD
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Homepagetest
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepagetestb" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepagetestB
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
=======
import { BrowserRouter as Router, Route, Routes } from "react-router-dom";
import Home from "./HomepageA";
import BlogPost from "./BlogPost";
import HomepageB from "./HomepageB";

const App = () => {
  return (
    <Router>
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/blogpost" element={<BlogPost />} />
        <Route path="/homepageb" element={<HomepageB />} />
      </Routes>
    </Router>
  );
};

export default Home;
>>>>>>> 149918b39c59d0d938156bf789d8820ff62cf335
